# Generated by Django 2.1.4 on 2019-01-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Plubished_date',
            new_name='Published_date',
        ),
    ]
