# Generated by Django 2.1.4 on 2019-01-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blblog', '0002_auto_20190103_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Published_date',
            new_name='published_date',
        ),
    ]
